### ISSUE TITLE
vim-SpellCheck mappings are not created when used with vim-qf

### ISSUE THREAD

**Issue by RobertBuhren** [inkarkat/vim-SpellCheck#1]
When using vim-qf (https://github.com/romainl/vim-qf) together with SpellCheck, the SpellCheck specific quickfix mappings are not created (e.g. "z=" uses the word under the cursor in the quickfix window and not the actual spelling error found by the spell check). 

Regards,
Robert

**Comment by inkarkat** [comment]
Is there something I can do to better coexist with vim-qf? It appears that the issue is rather with the other plugin; it even has a disclaimer right at the top:

> Vim-qf and all quickfix-related plugins necessarily have overlapping features and thus undefined behaviors.

**Comment by RobertBuhren** [comment]
I have noticed that the vim-SpellCheck mappings do actually work. But not the first time the quickfix window is opened. vim-qf will (in the default configuration) open the quickfix window automatically when there's content. 

When I execute ":SpellCheck" with vim-qf enabled, the quickfix will be automatically opened but there are no SpellCheck mappings available. However, when I set "let g:qf_auto_open_quickfix = 1" (i.e. disable the auto_open feature) and then manually open the quickfix window, the SpellCheck mappings are indeed there. 

I suspect that the autocmds in "plugin/SpellCheck.vim" do not work correctly when used with the vim-qf "auto_open_quickfix" feature. 

I'll investigate a little more tomorrow.

Regards,

Robert
On a side note:
Would it be possible for SpellCheck to use a dedicated window instead of the quickfix window?

**Comment by RobertBuhren** [comment]
I found the issue. When opening the qf window automatically, vim-qf uses the following autocmds:

`    autocmd QuickFixCmdPost [^l]* call qf#OpenQuickfix()
autocmd QuickFixCmdPost l* call qf#OpenLoclist()`

https://github.com/romainl/vim-qf/blob/master/plugin/qf.vim#L60-L61

As the 'nested' keyword is missing, the BufRead event is never triggered and the SpellCheck mappings are not created.

Regards,

Robert

**Comment by inkarkat** [comment]
Good analysis! Yes, adding `nested` in the vim-qf plugin should fix the problem. Please open an issue at vim-qf to get this fixed.

>  Would it be possible for SpellCheck to use a dedicated window instead of the quickfix window?

What would be the benefit of that? With quickfix or location lists, one gets the navigation and window management commands for free (and global scope / association to a window). By using a custom scratch buffer, one would have to implement all of that oneself.
