### ISSUE TITLE
doesn't work at all

### ISSUE THREAD

**Issue by oprogramador** [inkarkat/vim-SpellCheck#4]
OS: Mac OS X 10.12.6

I'm using [pathogen](https://github.com/tpope/vim-pathogen) and I cloned this repo into `~/.vim/bundle`.

I get:
```
⟩ vim
Error detected while processing /Users/me/.vim/bundle/vim-SpellCheck/plugin/SpellCheck.vim:
line  106:
E117: Unknown function: ingo#plugin#cmdcomplete#MakeFixedListCompleteFunc
Press ENTER or type command to continue
```
and I see no spell checking.

**Comment by inkarkat** [comment]
You also need to install the [ingo-library plugin](http://www.vim.org/scripts/script.php?script_id=4433) (or via [GitHub](https://github.com/inkarkat/vim-ingo-library)). It's listed in the [dependencies](https://github.com/inkarkat/vim-SpellCheck#dependencies). This library contains common autoload functions that are used by almost all of my plugins; it avoids code duplication and versioning issues.
